Improve accuracy of GH statuses (#18)

diff --git a/.github/workflows/self-test.yml b/.github/workflows/self-test.yml
--- a/.github/workflows/self-test.yml
+++ b/.github/workflows/self-test.yml
@@ -11,7 +11,7 @@ env:
 
 jobs:
   self-test:
-    name: Self-test
+    name: Successes
     runs-on: ubuntu-latest
     steps:
 
@@ -29,9 +29,84 @@ jobs:
           namespace: github-actions
           deployment: www
           container: nginx
-          image: nginx:latest
+          image: ghcr.io/firehed/deploy-to-kubernetes-action/server:${{ github.event.pull_request.head.sha || github.sha }}
           token: ${{ secrets.GITHUB_TOKEN }}
           transient: ${{ github.event_name == 'pull_request' }}
           production: ${{ github.event_name == 'push' }}
           url: https://example.com/${{ github.ref }}
           environment: ${{ github.event_name == 'push' && 'production' || format('dev-{0}', github.ref) }}
+
+      - name: Run w/out waiting
+        uses: ./
+        with:
+          namespace: github-actions
+          deployment: fast-deploy
+          container: nginx
+          image: ghcr.io/firehed/deploy-to-kubernetes-action/server:${{ github.event.pull_request.head.sha || github.sha }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+          transient: ${{ github.event_name == 'pull_request' }}
+          production: ${{ github.event_name == 'push' }}
+          url: https://example.com/${{ github.ref }}
+          environment: ${{ github.event_name == 'push' && 'production' || format('dev-{0}', github.ref) }}
+          wait: false
+
+#       - name: Run w/ very fast timeout
+#         uses: ./
+#         with:
+#           namespace: github-actions
+#           deployment: www
+#           container: nginx
+#           image: nginx:latest
+#           token: ${{ secrets.GITHUB_TOKEN }}
+#           transient: false
+#           production: false
+#           url: https://example.com/${{ github.ref }}
+#           environment: pr-selftest-fast-timeout
+#           wait-timeout: 2s
+
+  intentional-failures:
+    name: Failures
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    strategy:
+      max-parallel: 1 # Avoid trampling actual cluster resource
+      matrix:
+        include:
+
+          - name: Permissions (namespace)
+            env: pr-selftest-nopermissions
+            namespace: incorrect
+
+          - name: Deploy does not exist
+            env: pr-selftest-nodeploy
+            deployment: fake
+
+          - name: Bad image
+            env: pr-selftest-badimage
+            image: ghcr.io/firehed/deploy-to-kubernetes-action/badname:${{ github.sha }}
+
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v2
+
+      - name: Authenticate to cluster
+        run: echo ${{ secrets.KUBECONFIG_LKE }} | base64 -d > $KUBECONFIG
+
+      - name: ${{ matrix.name }}
+        uses: ./
+        id: test
+        continue-on-error: true
+        with:
+          namespace: ${{ matrix.namespace || 'github-actions' }}
+          container: nginx
+          deployment: ${{ matrix.deployment || 'failtest' }}
+          image: ${{ matrix.image || 'nginx:latest' }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+          environment: ${{ matrix.env }}
+          transient: false
+          production: false
+          wait-timeout: 10s # Just to fail in a reasonable amount of time
+
+      - name: Failing step must fail
+        if: steps.test.outcome != 'failure'
+        run: exit 1
